// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceManageGroup.Data;

#nullable disable

namespace ResourceManageGroup.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("EmployeeSequence", "dbo");

            modelBuilder.HasSequence<int>("ManagerSequence", "dbo");

            modelBuilder.HasSequence<int>("RecruiterSequence", "dbo");

            modelBuilder.Entity("ResourceManageGroup.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("CONCAT('23EM', RIGHT('00' + CAST(NEXT VALUE FOR EmployeeSequence AS VARCHAR(2)), 2))");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmployeeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTechnology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTrainerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTrainingEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeTrainingStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeVacationEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeVacationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeVacationStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeVacationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeWorkingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee_Details");
                });

            modelBuilder.Entity("ResourceManageGroup.Models.Manager", b =>
                {
                    b.Property<string>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("CONCAT('23PM', RIGHT('00' + CAST(NEXT VALUE FOR ManagerSequence AS VARCHAR(2)), 2))");

                    b.Property<string>("ManagerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.ToTable("Manager_Details");
                });

            modelBuilder.Entity("ResourceManageGroup.Models.Project", b =>
                {
                    b.Property<int>("project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("project_id"));

                    b.Property<string>("project_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_end_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_lead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_start_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("project_id");

                    b.ToTable("Project_Details");
                });

            modelBuilder.Entity("ResourceManageGroup.Models.Recruiter", b =>
                {
                    b.Property<string>("RecruiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("CONCAT('23HR', RIGHT('00' + CAST(NEXT VALUE FOR RecruiterSequence AS VARCHAR(2)), 2))");

                    b.Property<string>("RecruiterEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecruiterId");

                    b.ToTable("Recruiter_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
